public enum DIM_KEYS {
    DIM_COIL,
    DIM_DYN,
    DIM_INDIRECT_0,
    DIM_INDIRECT_1,
    DIM_INDIRECT_2,
    DIM_PHASE_CYCLE,
    DIM_EDIT,
    DIM_MEAS,
    DIM_USER_0,
    DIM_USER_1,
    DIM_USER_2,
}
